# Generated by Django 4.2.7 on 2025-06-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='is_verified',
            field=models.BooleanField(default=True, verbose_name='مُتحقق منه'),
        ),
    ]
