# Generated by Django 4.2.7 on 2025-06-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0003_barbershop_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='صورة الخدمة'),
        ),
    ]
