# Generated by Django 4.2.7 on 2025-07-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0006_barbershop_current_queue_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='current_queue_number',
        ),
    ]
