name: barbershop
services:
- name: web
  source_dir: /
  github:
    repo: devil0px/Barbershop
    branch: main
    deploy_on_push: true
  run_command: |
    python manage.py collectstatic --noinput
    python manage.py migrate --noinput
    gunicorn project.wsgi:application --bind 0.0.0.0:$PORT
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8080"
  - key: DEBUG
    value: "False"
  - key: SECRET_KEY
    value: "your-production-secret-key-here"
  - key: ALLOWED_HOSTS
    value: ".ondigitalocean.app,localhost,127.0.0.1"
  - key: DATABASE_URL
    value: "${db.DATABASE_URL}"

databases:
- name: db
  engine: PG
  version: "15"
  size: basic

