name: barbershop-management-system
services:
- name: web
  source_dir: /
  github:
    repo: devil0px/Barbershop
    branch: main
    deploy_on_push: true
  build_command: |
    pip install -r requirements.txt
  run_command: |
    cd src && python manage.py collectstatic --noinput && python manage.py migrate --noinput && python start_server.py
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  routes:
  - path: /
  envs:
  - key: PORT
    value: "8080"
  - key: DEBUG
    value: "True"
  - key: SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
  - key: ALLOWED_HOSTS
    value: ".ondigitalocean.app,.herokuapp.com,.railway.app,localhost,127.0.0.1"
  # Database will use SQLite (no external database needed)
  # - key: DATABASE_URL
  #   value: "${db.DATABASE_URL}"
  # - key: REDIS_URL
  #   value: "${redis.REDIS_URL}"
  - key: EMAIL_HOST_USER
    scope: RUN_TIME
    type: SECRET
  - key: EMAIL_HOST_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: GOOGLE_CLIENT_ID
    scope: RUN_TIME
    type: SECRET
  - key: GOOGLE_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: DEFAULT_FROM_EMAIL
    value: "Barber Shop <noreply@yourdomain.com>"
  - key: SITE_DOMAIN
    value: "yourdomain.com"
  - key: CSRF_TRUSTED_ORIGINS
    value: "https://${APP_DOMAIN}"
  - key: CORS_ALLOWED_ORIGINS
    value: "https://${APP_DOMAIN}"

# No external databases needed - using SQLite
# databases:
# - name: db
#   engine: PG
#   version: "15"
#   size: basic
# 
# - name: redis
#   engine: REDIS
#   version: "7"
#   size: basic

