# Generated by Django 4.2.7 on 2025-06-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('barber', 'صاحب محل حلاقة')], default='customer', max_length=10, verbose_name='نوع المستخدم'),
        ),
    ]
