# Generated by Django 5.2.3 on 2025-07-27 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, help_text='يجب أن يكون فريدًا.', max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='أدخل رقم هاتف صالح.', regex='^\\+?1?\\d{9,15}$')], verbose_name='رقم الهاتف'),
        ),
    ]
