# Generated by Django 5.2.3 on 2025-07-27 14:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('customer', 'عميل'), ('barber', 'صاحب محل حلاقة')], default='customer', max_length=10, null=True, verbose_name='نوع المستخدم'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=uuid.uuid4, error_messages={'unique': 'A user with that username already exists.'}, max_length=150, unique=True),
        ),
    ]
