# Generated by Django 5.2.3 on 2025-08-02 07:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_profile_photo_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activation_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='كود التفعيل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_code_created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ إنشاء كود التفعيل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='activation_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='رمز التفعيل'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_email_verified',
            field=models.BooleanField(default=False, verbose_name='تم تفعيل الإيميل'),
        ),
    ]
