# Generated by Django 4.2.7

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('subtitle', models.TextField(verbose_name='العنوان الفرعي')),
                ('background_image', models.ImageField(upload_to='hero_slides/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='صورة الخلفية')),
                ('button_text', models.CharField(default='احجز الآن', max_length=50, verbose_name='نص الزر')),
                ('button_url', models.CharField(default='/barbershops/', max_length=200, verbose_name='رابط الزر')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'شريحة البانر',
                'verbose_name_plural': 'شرائح البانر',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomePageFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('icon', models.CharField(default='fas fa-check-circle', help_text='مثال: fas fa-check-circle', max_length=50, verbose_name='أيقونة (Font Awesome class)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ميزة الصفحة الرئيسية',
                'verbose_name_plural': 'ميزات الصفحة الرئيسية',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Barber Shop', max_length=100, verbose_name='اسم الموقع')),
                ('site_description', models.TextField(default='أفضل صالون حلاقة في المدينة', verbose_name='وصف الموقع')),
                ('hero_title', models.CharField(default='أفضل صالون حلاقة في المدينة', max_length=200, verbose_name='عنوان البانر الرئيسي')),
                ('hero_subtitle', models.TextField(default='منذ عام 1973، نقدم خدمات حلاقة عالية الجودة مع التركيز على الحرفية والاهتمام بالتفاصيل.', verbose_name='وصف البانر الرئيسي')),
                ('about_title', models.CharField(default='خبرة تمتد لأكثر من 50 عاماً', max_length=200, verbose_name='عنوان قسم عنا')),
                ('about_description', models.TextField(default='منذ عام 1973، نحن نقدم أفضل خدمات الحلاقة في المدينة. فريقنا من الحلاقين المحترفين يجمع بين التقنيات التقليدية والأساليب الحديثة لنمنحك مظهراً مميزاً.', verbose_name='وصف قسم عنا')),
                ('about_image_1', models.ImageField(blank=True, null=True, upload_to='about_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='الصورة الأولى')),
                ('about_image_1_alt', models.CharField(default='صورة المحل', max_length=100, verbose_name='وصف الصورة الأولى')),
                ('about_image_2', models.ImageField(blank=True, null=True, upload_to='about_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='الصورة الثانية')),
                ('about_image_2_alt', models.CharField(default='فريق العمل', max_length=100, verbose_name='وصف الصورة الثانية')),
                ('about_image_3', models.ImageField(blank=True, null=True, upload_to='about_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='الصورة الثالثة')),
                ('about_image_3_alt', models.CharField(default='أدوات الحلاقة', max_length=100, verbose_name='وصف الصورة الثالثة')),
                ('phone_number', models.CharField(default='+20109841514', max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(default='info@barbershop.com', max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(default='مدينتي - اسم الشارع', max_length=200, verbose_name='العنوان')),
                ('working_hours', models.CharField(default='يومياً من 8:00 ص إلى 10:00 م', max_length=100, verbose_name='ساعات ا��عمل')),
                ('facebook_url', models.URLField(blank=True, null=True, verbose_name='رابط فيسبوك')),
                ('instagram_url', models.URLField(blank=True, null=True, verbose_name='رابط إنستغرام')),
                ('twitter_url', models.URLField(blank=True, null=True, verbose_name='رابط تويتر')),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم واتساب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='اسم العميل')),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='testimonials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='صورة العميل')),
                ('testimonial_text', models.TextField(verbose_name='نص الشهادة')),
                ('rating', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5, verbose_name='التقييم')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='المنصب/الوظيفة')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'شهادة عميل',
                'verbose_name_plural': 'شهادات العملاء',
                'ordering': ['-is_featured', 'order', '-created_at'],
            },
        ),
    ]