# Generated by Django 5.2.3 on 2025-08-02 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-is_featured', 'order', '-created_at'], 'verbose_name': 'شهادة عميل', 'verbose_name_plural': 'شهادات الع��لاء'},
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='working_hours',
            field=models.CharField(default='يومياً من 8:00 ص إلى 10:00 م', max_length=100, verbose_name='ساعات العمل'),
        ),
    ]
