# Generated by Django 4.2.7 on 2025-07-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_bookinghistory_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-booking_day', 'queue_number'], 'verbose_name': 'حجز', 'verbose_name_plural': 'الحجوزات'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_day',
            field=models.DateField(blank=True, null=True, verbose_name='اليوم المحجوز له'),
        ),
        migrations.AddField(
            model_name='booking',
            name='queue_number',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم الدور في اليوم'),
        ),
    ]
