# Generated by Django 5.2.3 on 2025-08-04 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0009_barbershop_current_turn_number_and_more'),
        ('bookings', '0006_alter_booking_options_remove_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barbershops.service', verbose_name='الخدمة'),
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='الكمية')),
                ('price_at_booking', models.DecimalField(decimal_places=2, help_text='سعر الخدمة وقت إنشاء الحجز', max_digits=8, verbose_name='السعر وقت الحجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات خاصة بالخدمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_services', to='bookings.booking', verbose_name='الحجز')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_bookings', to='barbershops.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'خدمة الحجز',
                'verbose_name_plural': 'خدمات الحجوزات',
                'ordering': ['created_at'],
                'unique_together': {('booking', 'service')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='services',
            field=models.ManyToManyField(related_name='multi_bookings', through='bookings.BookingService', to='barbershops.service', verbose_name='الخدمات المحجوزة'),
        ),
    ]
