# Generated by Django 5.2.3 on 2025-06-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbershops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(verbose_name='تاريخ الحجز')),
                ('booking_time', models.TimeField(verbose_name='وقت الحجز')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='pending', max_length=20, verbose_name='حالة الحجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='السعر الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barbershops.barbershop', verbose_name='محل الحلاقة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='العميل')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='barbershops.service', verbose_name='الخدمة')),
            ],
            options={
                'verbose_name': 'حجز',
                'verbose_name_plural': 'الحجوزات',
                'ordering': ['-booking_date', '-booking_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='bookings.booking', verbose_name='الحجز')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
            ],
            options={
                'verbose_name': 'تاريخ الحجز',
                'verbose_name_plural': 'تاريخ الحجوزات',
                'ordering': ['-created_at'],
            },
        ),
    ]
