# Generated by Django 4.2.7 on 2025-06-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookingmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookinghistory',
            name='status',
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='new_status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة الجديدة'),
        ),
        migrations.AddField(
            model_name='bookinghistory',
            name='old_status',
            field=models.CharField(choices=[('pending', 'في الانتظار'), ('confirmed', 'مؤكد'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('no_show', 'لم يحضر')], default='pending', max_length=20, verbose_name='الحالة السابقة'),
        ),
    ]
