# Generated by Django 4.2.7 on 2025-06-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0002_alter_barbershop_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='barbershops/', verbose_name='صورة المحل'),
        ),
    ]
