# Generated by Django 4.2.7 on 2025-06-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0004_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='allow_customer_photos',
            field=models.BooleanField(default=True, verbose_name='السماح بتحميل صور العملاء'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='allow_online_booking',
            field=models.BooleanField(default=True, verbose_name='السماح بالحجز عبر الإنترنت'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='booking_advance_days',
            field=models.PositiveIntegerField(default=7, verbose_name='عدد الأيام المسموح بها للحجز المسبق'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='booking_slots',
            field=models.JSONField(default=dict, verbose_name='أوقات الحجز المتاحة'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='اسم المستخدم على انستغرام'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='محل مميز'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='max_customer_photos',
            field=models.PositiveIntegerField(default=5, verbose_name='الحد الأقصى لصور العملاء'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='maximum_booking_time',
            field=models.PositiveIntegerField(default=120, verbose_name='الحد الأقصى لوقت الحجز (دقائق)'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='minimum_booking_time',
            field=models.PositiveIntegerField(default=30, verbose_name='الحد الأدنى لوقت الحجز (دقائق)'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='minimum_rating_for_review',
            field=models.PositiveIntegerField(default=1, verbose_name='التقييم الأدنى المسموح به'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='notify_by_email',
            field=models.BooleanField(default=True, verbose_name='إشعارات بالبريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='notify_by_sms',
            field=models.BooleanField(default=True, verbose_name='إشعارات بالرسائل القصيرة'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='notify_by_whatsapp',
            field=models.BooleanField(default=True, verbose_name='إشعارات على واتساب'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='premium_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء المميز'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='require_photo_for_review',
            field=models.BooleanField(default=False, verbose_name='السماح بالصور في التقييمات'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='settings',
            field=models.JSONField(default=dict, verbose_name='الإعدادات المتقدمة'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='theme_color',
            field=models.CharField(default='#007bff', max_length=7, verbose_name='لون الموضوع'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم واتساب'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='working_days',
            field=models.JSONField(default=dict, verbose_name='أيام العمل'),
        ),
        migrations.AddField(
            model_name='service',
            name='available_days',
            field=models.JSONField(default=dict, verbose_name='أيام توفر الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='available_hours',
            field=models.JSONField(default=dict, verbose_name='ساعات توفر الخدمة'),
        ),
        migrations.AddField(
            model_name='service',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='متوسط التقييم'),
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('haircut', 'قص الشعر'), ('beard', 'اللحية'), ('shave', 'الحلاقة'), ('hair_color', 'صبغ الشعر'), ('other', 'خدمات أخرى')], default='haircut', max_length=50, verbose_name='الفئة'),
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.PositiveIntegerField(default=0, verbose_name='ترتيب العرض'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='خدمة شائعة'),
        ),
        migrations.AddField(
            model_name='service',
            name='max_booking_time',
            field=models.PositiveIntegerField(default=120, verbose_name='الحد الأقصى لوقت الحجز (دقائق)'),
        ),
        migrations.AddField(
            model_name='service',
            name='min_booking_time',
            field=models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى لوقت الحجز (دقائق)'),
        ),
        migrations.AddField(
            model_name='service',
            name='popularity_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درجة الشهرة'),
        ),
        migrations.AddField(
            model_name='service',
            name='preparation_time',
            field=models.PositiveIntegerField(default=0, verbose_name='وقت التحضير (دقائق)'),
        ),
        migrations.AddField(
            model_name='service',
            name='required_tools',
            field=models.TextField(blank=True, verbose_name='الأدوات المطلوبة'),
        ),
        migrations.AddField(
            model_name='service',
            name='total_bookings',
            field=models.PositiveIntegerField(default=0, verbose_name='إجمالي الحجوزات'),
        ),
    ]
