# Generated by Django 4.2.7 on 2025-07-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0005_barbershop_allow_customer_photos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='current_queue_number',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم الدور الحالي'),
        ),
    ]
