# Generated by Django 5.2.3 on 2025-07-27 20:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0007_remove_barbershop_current_queue_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='barbershop',
            unique_together={('owner', 'name')},
        ),
    ]
