# Generated by Django 5.2.3 on 2025-07-30 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0008_alter_barbershop_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='current_turn_number',
            field=models.IntegerField(default=0, help_text='الرقم الذي يتم خدمته حالياً في المحل.', verbose_name='رقم الدور الحالي'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
